# NLP Intent Constants (v1.0)

GET_SALES_SUMMARY = "GET_SALES_SUMMARY"
GET_OUTSTANDING_PAYMENTS = "GET_OUTSTANDING_PAYMENTS"
GET_LOW_STOCK_ITEMS = "GET_LOW_STOCK_ITEMS"
GET_DAILY_BUSINESS_SUMMARY = "GET_DAILY_BUSINESS_SUMMARY"
GET_PURCHASE_OVERVIEW = "GET_PURCHASE_OVERVIEW"

SUPPORTED_LANGUAGES = ["en", "hi"]
